### ISSUE TITLE
Cannot find module darknet.node

### ISSUE THREAD

**Issue by DrewDaPilot** [bennetthardwick/darknet.js#40]
When executing a fresh install on ubuntu, (using WSL), I get the following exception:

`drew@DESKTOP-LEGTF2V:/mnt/c/Users/Drew/WebstormProjects/project1$ node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './build/Release/darknet.node'
Require stack:
- /mnt/c/Users/Drew/WebstormProjects/project1/node_modules/darknet/darknet.js
- /mnt/c/Users/Drew/WebstormProjectsproject1/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/mnt/c/Users/Drew/WebstormProjects/project1/node_modules/darknet/darknet.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Users/Drew/WebstormProjects/project1/node_modules/darknet/darknet.js',
    '/mnt/c/Users/Drew/WebstormProjects/project1/index.js'
  ]
}
`

It appears that the native node module that should have been compiled wasn't compiled, or it is not in the correct directory. Any advice on the matter would be much appreciated.

**Comment by DrewDaPilot** [comment]
Apparently it turns out that the issue was completely to do with me upgrading nodejs. I re-ran `npm i` and it worked. Sorry for the troubles.
